export const sidebar = [
  "menu",
  "actions",
  "animals",
  "animals2",
  "clothes",
  "digits",
  "food",
  "fruits",
  "nature",
  "stats",
];

export const menu = [
  {
    word: "actions",
    img: "../assets/img/menu/actions.png",
  },
  {
    word: "animals",
    img: "../assets/img/menu/animals.png",
  },
  {
    word: "animals2",
    img: "../assets/img/menu/animals2.png",
  },
  {
    word: "clothes",
    img: "../assets/img/menu/clothes.png",
  },
  {
    word: "digits",
    img: "../assets/img/menu/digits.png",
  },
  {
    word: "food",
    img: "../assets/img/menu/food.png",
  },
  {
    word: "fruits",
    img: "../assets/img/menu/fruits.png",
  },
  {
    word: "nature",
    img: "../assets/img/menu/nature.png",
  },
];

export const actions = [
  {
    word: "cry",
    translation: "плакаць",
    img: "../assets/img/actions/cry.png",
    audio: "../assets/audio/cry.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "dance",
    translation: "танчыць",
    img: "../assets/img/actions/dance.png",
    audio: "../assets/audio/dance.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "dive",
    translation: "ныраць",
    img: "../assets/img/actions/dive.png",
    audio: "../assets/audio/dive.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "draw",
    translation: "маляваць",
    img: "../assets/img/actions/draw.png",
    audio: "../assets/audio/draw.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "fish",
    translation: "рыбачыць",
    img: "../assets/img/actions/fish.png",
    audio: "../assets/audio/fish.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "fly",
    translation: "лятаць",
    img: "../assets/img/actions/fly.png",
    audio: "../assets/audio/fly.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "hug",
    translation: "абдымаць",
    img: "../assets/img/actions/hug.png",
    audio: "../assets/audio/hug.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "laugh",
    translation: "смяяцца",
    img: "../assets/img/actions/laugh.png",
    audio: "../assets/audio/laugh.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const animals = [
  {
    word: "cat",
    translation: "кот",
    img: "../assets/img/animals/cat.png",
    audio: "../assets/audio/cat.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "chicken",
    translation: "курыца",
    img: "../assets/img/animals/chicken.png",
    audio: "../assets/audio/chicken.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "dog",
    translation: "сабака",
    img: "../assets/img/animals/dog.png",
    audio: "../assets/audio/dog.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "dolphin",
    translation: "дэльфiн",
    img: "../assets/img/animals/dolphin.png",
    audio: "../assets/audio/dolphin.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "fish",
    translation: "рыба",
    img: "../assets/img/animals/fish.png",
    audio: "../assets/audio/fish.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "frog",
    translation: "жаба",
    img: "../assets/img/animals/frog.png",
    audio: "../assets/audio/frog.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "horse",
    translation: "конь",
    img: "../assets/img/animals/horse.png",
    audio: "../assets/audio/horse.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "turtle",
    translation: "чарапаха",
    img: "../assets/img/animals/turtle.png",
    audio: "../assets/audio/turtle.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const animals2 = [
  {
    word: "bird",
    translation: "птушка",
    img: "../assets/img/animals2/bird.png",
    audio: "../assets/audio/bird.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "cow",
    translation: "карова",
    img: "../assets/img/animals2/cow.png",
    audio: "../assets/audio/cow.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "giraffe",
    translation: "жырафа",
    img: "../assets/img/animals2/giraffe.png",
    audio: "../assets/audio/giraffe.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "lion",
    translation: "леў",
    img: "../assets/img/animals2/lion.png",
    audio: "../assets/audio/lion.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "mouse",
    translation: "мыш",
    img: "../assets/img/animals2/mouse.png",
    audio: "../assets/audio/mouse.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "pig",
    translation: "свіння",
    img: "../assets/img/animals2/pig.png",
    audio: "../assets/audio/pig.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "rabbit",
    translation: "трус",
    img: "../assets/img/animals2/rabbit.png",
    audio: "../assets/audio/rabbit.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "sheep",
    translation: "авечка",
    img: "../assets/img/animals2/sheep.png",
    audio: "../assets/audio/sheep.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const clothes = [
  {
    word: "blouse",
    translation: "блузка",
    img: "../assets/img/clothes/blouse.png",
    audio: "../assets/audio/blouse.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "boot",
    translation: "чаравік",
    img: "../assets/img/clothes/boot.png",
    audio: "../assets/audio/boot.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "coat",
    translation: "паліто",
    img: "../assets/img/clothes/coat.png",
    audio: "../assets/audio/coat.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "dress",
    translation: "сукенка",
    img: "../assets/img/clothes/dress.png",
    audio: "../assets/audio/dress.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "pants",
    translation: "штаны",
    img: "../assets/img/clothes/pants.png",
    audio: "../assets/audio/pants.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "shirt",
    translation: "кашуля",
    img: "../assets/img/clothes/shirt.png",
    audio: "../assets/audio/shirt.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "shoe",
    translation: "туфлі",
    img: "../assets/img/clothes/shoe.png",
    audio: "../assets/audio/shoe.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "skirt",
    translation: "спадніца",
    img: "../assets/img/clothes/skirt.png",
    audio: "../assets/audio/skirt.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const digits = [
  {
    word: "six",
    translation: "шэсць",
    img: "../assets/img/digits/six.png",
    audio: "../assets/audio/six.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "two",
    translation: "два",
    img: "../assets/img/digits/two.png",
    audio: "../assets/audio/two.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "eight",
    translation: "восем",
    img: "../assets/img/digits/eight.png",
    audio: "../assets/audio/eight.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "four",
    translation: "чатыры",
    img: "../assets/img/digits/four.png",
    audio: "../assets/audio/four.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "seven",
    translation: "сем",
    img: "../assets/img/digits/seven.png",
    audio: "../assets/audio/seven.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "one",
    translation: "адзiн",
    img: "../assets/img/digits/one.png",
    audio: "../assets/audio/one.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "five",
    translation: "пяць",
    img: "../assets/img/digits/five.png",
    audio: "../assets/audio/five.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "three",
    translation: "тры",
    img: "../assets/img/digits/three.png",
    audio: "../assets/audio/three.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const food = [
  {
    word: "bread",
    translation: "хлеб",
    img: "../assets/img/food/bread.png",
    audio: "../assets/audio/bread.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "eggs",
    translation: "яйкi",
    img: "../assets/img/food/eggs.png",
    audio: "../assets/audio/eggs.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "pasta",
    translation: "макароны",
    img: "../assets/img/food/pasta.png",
    audio: "../assets/audio/pasta.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "pizza",
    translation: "пiца",
    img: "../assets/img/food/pizza.png",
    audio: "../assets/audio/pizza.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "potato",
    translation: "бульба",
    img: "../assets/img/food/potato.png",
    audio: "../assets/audio/potato.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "salad",
    translation: "салата",
    img: "../assets/img/food/salad.png",
    audio: "../assets/audio/salad.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "sushi",
    translation: "сушы",
    img: "../assets/img/food/sushi.png",
    audio: "../assets/audio/sushi.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "vegetables",
    translation: "гароднiна",
    img: "../assets/img/food/vegetables.png",
    audio: "../assets/audio/vegetables.mp3",
    correct: 0,
    mistakes: 0,
  },
];
export const fruits = [
  {
    word: "apple",
    translation: "яблык",
    img: "../assets/img/fruits/apple.png",
    audio: "../assets/audio/apple.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "banana",
    translation: "банан",
    img: "../assets/img/fruits/banana.png",
    audio: "../assets/audio/banana.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "kiwi",
    translation: "ківі",
    img: "../assets/img/fruits/kiwi.png",
    audio: "../assets/audio/kiwi.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "mandarin",
    translation: "мандарын",
    img: "../assets/img/fruits/mandarin.png",
    audio: "../assets/audio/mandarin.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "orange",
    translation: "апельсін",
    img: "../assets/img/fruits/orange.png",
    audio: "../assets/audio/orange.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "pineapple",
    translation: "ананас",
    img: "../assets/img/fruits/pineapple.png",
    audio: "../assets/audio/pineapple.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "strawberry",
    translation: "трускаўка",
    img: "../assets/img/fruits/strawberry.png",
    audio: "../assets/audio/strawberry.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "watermelon",
    translation: "кавун",
    img: "../assets/img/fruits/watermelon.png",
    audio: "../assets/audio/watermelon.mp3",
    correct: 0,
    mistakes: 0,
  },
];

export const nature = [
  {
    word: "fire",
    translation: "агонь",
    img: "../assets/img/nature/fire.png",
    audio: "../assets/audio/fire.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "forest",
    translation: "лес",
    img: "../assets/img/nature/forest.png",
    audio: "../assets/audio/forest.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "grass",
    translation: "трава",
    img: "../assets/img/nature/grass.png",
    audio: "../assets/audio/grass.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "sand",
    translation: "пясок",
    img: "../assets/img/nature/sand.png",
    audio: "../assets/audio/sand.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "sky",
    translation: "неба",
    img: "../assets/img/nature/sky.png",
    audio: "../assets/audio/sky.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "snow",
    translation: "снег",
    img: "../assets/img/nature/snow.png",
    audio: "../assets/audio/snow.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "sunset",
    translation: "захад",
    img: "../assets/img/nature/sunset.png",
    audio: "../assets/audio/sunset.mp3",
    correct: 0,
    mistakes: 0,
  },
  {
    word: "water",
    translation: "вада",
    img: "../assets/img/nature/water.png",
    audio: "../assets/audio/water.mp3",
    correct: 0,
    mistakes: 0,
  },
];

export const constantsArray = [
  menu,
  actions,
  animals,
  animals2,
  clothes,
  digits,
  food,
  fruits,
  nature,
];
export const tableHeaders = [
  "word",
  "category",
  "translation",
  "trained",
  "correct",
  "mistakes",
  "mistakes, %",
];

export const correctAnswerSound = new Audio("../assets/audio/correct.mp3");
export const wrongAnswerSound = new Audio("../assets/audio/wrong.mp3");
export const successSound = new Audio("../assets/audio/win_sound.mp3");
export const failureSound = new Audio("../assets/audio/lose_sound.mp3");
